# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Ang Li"
description              : #"Major in Computer Science & Technology."
repository               : "chris-Ang-li/chris-Ang-li.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      : #283511074

# SEO Related
google_site_verification : EPFJbnyGpGwvvQEW7huw6tFZW
bing_site_verification   : ED1FA53D8C53BF8001369CB0F1F99542
baidu_site_verification  : #code-ZxFK3f4pfb

# Site Author
author:
  name             : "Ang Li"
  avatar           : "images/angli_profile.jpg"
  bio              : "Postdoctoral Researcher, The Chinese University of Hong Kong, Shenzhen"
  location         : #"Shenzhen, China"
  employer         : CUHK-Shenzhen
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=p2ohnUYAAAAJ&hl=en"
  email            : "chrisangli@cuhk.edu.cn"
  researchgate     : #"xxx"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : #"xxx"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"xxx"
  lastfm           :
  linkedin         : #"xxx"
  dblp             : "https://dblp.org/pid/33/2805-15.html"
  orcid            : "https://orcid.org/0000-0002-2316-4118"
  pinterest        :
  soundcloud       :
  stackoverflow    : # xxx
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
  - google_scholar_crawler
  - github_myprofile_updater
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
